"use strict";
const clustersConfig = {
    "Clusters": {
        "Cluster": [
            {
                "Name": "BN1-0",
                "RestServerUri": "http://RestServer0-iVIP.Yarn3-Dev-Bn1.BN1.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn3-dev-bn1.bn1.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.yarn3-dev-bn1.bn1.ap.gbl",
                "HttpFSUri": "https://proxy1-ivip.yarn3-dev-bn1.bn1.ap.gbl:83",
                "resourceManagerUri": "http://resourcemanager0-ivip.yarn3-dev-bn1.bn1.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy0-ivip.yarn3-dev-bn1.bn1.ap.gbl:81",
                "subCluster": "BASIC-DEV-BN1-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn3-dev-bn1.bn1.ap.gbl:82",
            },
            {
                "Name": "CH1-0",
                "RestServerUri": "http://RestServer0-iVIP.Yarn-Prod-Ch1.Ch1.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1.ch1.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.yarn-prod-ch1.ch1.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1.ch1.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1',
                "resourceManagerUri": "http://resourcemanager0-ivip.yarn-prod-ch1.ch1.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy0-ivip.yarn-prod-ch1.ch1.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1.ch1.ap.gbl:82",
            },
            {
                "Name": "CH1-1",
                "RestServerUri": "http://RestServer1-iVIP.Yarn-Prod-Ch1.Ch1.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1.ch1.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.yarn-prod-ch1.ch1.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1.ch1.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.yarn-prod-ch1.ch1.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy1-ivip.yarn-prod-ch1.ch1.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1.ch1.ap.gbl:82",
            },
            {
                "Name": "BN1-1",
                "RestServerUri": "http://RestServer1-iVIP.Yarn3-Dev-Bn1.BN1.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn3-dev-bn1.bn1.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.yarn3-dev-bn1.bn1.ap.gbl",
                "HttpFSUri": "https://proxy1-ivip.yarn3-dev-bn1.bn1.ap.gbl:83",
                "resourceManagerUri": "http://resourcemanager1-ivip.yarn3-dev-bn1.bn1.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy1-ivip.yarn3-dev-bn1.bn1.ap.gbl:81",
                "subCluster": "BASIC-DEV-BN1-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn3-dev-bn1.bn1.ap.gbl:82",
            },
            {
                "Name": "CO4-0",
                "RestServerUri": "http://RestServer0-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4',
                "resourceManagerUri": "http://resourcemanager0-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy0-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "CO4-1",
                "RestServerUri": "http://RestServer1-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy1-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "CO4-2",
                "RestServerUri": "http://RestServer2-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode2-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4-2',
                "resourceManagerUri": "http://resourcemanager2-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy2-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-2",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "CO4-3",
                "RestServerUri": "http://RestServer3-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode3-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4-3',
                "resourceManagerUri": "http://resourcemanager3-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy3-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-3",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "CO4-4",
                "RestServerUri": "http://RestServer4-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode4-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4-4',
                "resourceManagerUri": "http://resourcemanager4-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy4-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-4",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "CO4-5",
                "RestServerUri": "http://RestServer5-iVIP.Yarn-Prod-Co4.Co4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode5-ivip.yarn-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CO4-5',
                "resourceManagerUri": "http://resourcemanager5-ivip.yarn-prod-co4.co4.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy5-ivip.yarn-prod-co4.co4.ap.gbl:81",
                "subCluster": "BASIC-PROD-CO4-5",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "BN2-0",
                "RestServerUri": "http://RestServer0-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2',
                "resourceManagerUri": "http://resourcemanager0-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy0-ivip.yarn-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "BASIC-PROD-BN2-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "BN2-1",
                "RestServerUri": "http://RestServer1-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy1-ivip.yarn-prod-bn2.bn2.ap.gbl:81",          
                "subCluster": "BASIC-PROD-BN2-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "BN2-2",
                "RestServerUri": "http://RestServer2-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode2-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2-2',
                "resourceManagerUri": "http://resourcemanager2-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy2-ivip.yarn-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "BASIC-PROD-BN2-2",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "BN2-3",
                "RestServerUri": "http://RestServer3-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode3-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2-3',
                "resourceManagerUri": "http://resourcemanager3-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy3-ivip.yarn-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "BASIC-PROD-BN2-3",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "BN2-4",
                "RestServerUri": "http://RestServer4-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode4-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2-4',
                "resourceManagerUri": "http://resourcemanager4-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy4-ivip.yarn-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "BASIC-PROD-BN2-4",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "BN2-5",
                "RestServerUri": "http://RestServer5-iVIP.Yarn-Prod-Bn2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode5-ivip.yarn-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/BN2-5',
                "resourceManagerUri": "http://resourcemanager5-ivip.yarn-prod-bn2.bn2.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy5-ivip.yarn-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "BASIC-PROD-BN2-5",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "CH1B-0",
                "RestServerUri": "http://RestServer0-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B',
                "resourceManagerUri": "http://resourcemanager0-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy0-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "CH1B-1",
                "RestServerUri": "http://RestServer1-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy1-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "CH1B-2",
                "RestServerUri": "http://RestServer2-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode2-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B-2',
                "resourceManagerUri": "http://resourcemanager2-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy2-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-2",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "CH1B-3",
                "RestServerUri": "http://RestServer3-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode3-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B-3',
                "resourceManagerUri": "http://resourcemanager3-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy3-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-3",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "CH1B-4",
                "RestServerUri": "http://RestServer4-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode4-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B-4',
                "resourceManagerUri": "http://resourcemanager4-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy4-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-4",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "CH1B-5",
                "RestServerUri": "http://RestServer5-iVIP.Yarn-Prod-Ch1b.Ch1b.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode5-ivip.yarn-prod-ch1b.ch1b.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/CH1B-5',
                "resourceManagerUri": "http://resourcemanager5-ivip.yarn-prod-ch1b.ch1b.ap.gbl/cluster/apps/",
                "yarnProxyUri": "http://proxy5-ivip.yarn-prod-ch1b.ch1b.ap.gbl:81",
                "subCluster": "BASIC-PROD-CH1B-5",
                "sparkHistoryServerUri": "http://jobhistory-ivip.yarn-prod-ch1b.ch1b.ap.gbl:82",
            },
            {
                "Name": "MTPrime-CO4-0",
                "RestServerUri": "http://RestServer0-iVIP.MTPrime-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-CO4-0',
                "resourceManagerUri": "http://resourcemanager0-ivip.mtprime-prod-co4.co4.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy0-ivip.mtprime-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTPrime-PROD-CO4-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "MTPrime-CO4-1",
                "RestServerUri": "http://RestServer1-iVIP.MTPrime-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.mtprime-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-CO4-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.mtprime-prod-co4.co4.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy1-ivip.mtprime-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTPrime-PROD-CO4-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "MTPrime-CO4-2",
                "RestServerUri": "http://RestServer2-iVIP.MTPrime-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.mtprime-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-CO4-0',
                "resourceManagerUri": "http://resourcemanager2-ivip.mtprime-prod-co4.co4.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy2-ivip.mtprime-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTPrime-PROD-CO4-2",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "MTPrime-CO4-3",
                "RestServerUri": "http://RestServer3-iVIP.MTPrime-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode3-ivip.mtprime-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-CO4-3',
                "resourceManagerUri": "http://resourcemanager3-ivip.mtprime-prod-co4.co4.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy3-ivip.mtprime-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTPrime-PROD-CO4-3",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "MTPrime-CO4-4",
                "RestServerUri": "http://RestServer4-iVIP.MTPrime-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode4-ivip.mtprime-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-co4.co4.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-CO4-4',
                "resourceManagerUri": "http://resourcemanager4-ivip.mtprime-prod-co4.co4.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy4-ivip.mtprime-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTPrime-PROD-CO4-4",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-co4.co4.ap.gbl:82",
            },
            {
                "Name": "MTPrime-BN2-0",
                "RestServerUri": "http://RestServer0-iVIP.MTPrime-Prod-BN2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.mtprime-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-PROD-BN2-0',
                "resourceManagerUri": "http://resourcemanager0-ivip.mtprime-prod-bn2.bn2.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy0-ivip.mtprime-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "MTPrime-PROD-BN2-0",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "MTPrime-BN2-1",
                "RestServerUri": "http://RestServer1-iVIP.MTPrime-Prod-BN2.BN2.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode1-ivip.mtprime-prod-bn2.bn2.ap.gbl",
                "HttpFSUri": 'http://httpfs-ivip.mtprime-prod-bn2.bn2.ap.gbl:82',
                "HttpFSAPIPath": '/webhdfs/v1/MTPrime-BN2-1',
                "resourceManagerUri": "http://resourcemanager1-ivip.mtprime-prod-bn2.bn2.ap.gbl/cluster/apps",
                "yarnProxyUri": "http://proxy1-ivip.mtprime-prod-bn2.bn2.ap.gbl:81",
                "subCluster": "MTPrime-PROD-BN2-1",
                "sparkHistoryServerUri": "http://jobhistory-ivip.mtprime-prod-bn2.bn2.ap.gbl:82",
            },
            {
                "Name": "MTCmpl-CO4-0",
                "RestServerUri": "https://RestServer0-iVIP.MTCmpl-Prod-CO4.CO4.ap.gbl:9186",
                "WebPortalUri": "http://Webportal-iVIP.yarn-prod-ch1b.ch1b.ap.gbl:9286",
                "hdfsUri": "hdfs://namenode0-ivip.mtcmpl-prod-co4.co4.ap.gbl",
                "HttpFSUri": 'https://httpfs-ivip.mtcmpl-prod-co4.co4.ap.gbl:83',
                "HttpFSAPIPath": '/webhdfs/v1/MTCmpl-CO4-0',
                "resourceManagerUri": "https://resourcemanager0-ivip.mtcmpl-prod-co4.co4.ap.gbl:82/cluster/apps",
                "yarnProxyUri": "https://proxy0-ivip.mtcmpl-prod-co4.co4.ap.gbl:81",
                "subCluster": "MTCmpl-PROD-CO4-0",
                "sparkHistoryServerUri": "https://jobhistory-ivip.mtcmpl-prod-co4.co4.ap.gbl:482",
            },
        ]
    }
}

module.exports = clustersConfig;
